### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by jacob-bw** [jacob-bw/Insert-Knife#2]
## User Story
As a developer building an application with multiple data tables and randomized configurations, I want to begin the project with a clear vision of my data structure.

**Comment by jacob-bw** [comment]
![INSERT Knife - Final Capstone ERD](https://user-images.githubusercontent.com/51467735/86686571-14b61e00-bfca-11ea-881c-2b3f7d2273a1.png)

**Comment by copypastedeveloper** [comment]
👍

**Comment by jacob-bw** [comment]
v2 ERD updated w/ `isSolution` column on `Guess` table

![INSERT-Knife-FinalCapstoneERD v2](https://user-images.githubusercontent.com/51467735/86941264-5d282580-c109-11ea-9fc0-94a417574f10.png)

**Comment by jacob-bw** [comment]
v3 ERD updated w/ `savedGameId` added to `User` table

![INSERT-Knife-FinalCapstoneERD v3](https://user-images.githubusercontent.com/51467735/87226649-ca7ec500-c35a-11ea-8134-f7b5e44140e5.png)

**Comment by jacob-bw** [comment]
ERD v4 updated w/ `occupied` column added to `rooms` table. ![INSERT-Knife-FinalCapstoneERD v4](https://user-images.githubusercontent.com/51467735/89057196-dd196800-d322-11ea-80c0-598b07a84ee8.png)
