### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by jacob-bw** [jacob-bw/Insert-Knife#3]
## User Story
As a developer building an application I would like to see a rough approximation of what the webpage will look like to use as a guideline as I construct the application.

**Comment by jacob-bw** [comment]
![insertKnife Mockup v1](https://user-images.githubusercontent.com/51467735/86691840-d4a56a00-bfce-11ea-9c01-e251feb18bb9.png)

**Comment by copypastedeveloper** [comment]
love it 🚀
